# -
# Global configuration
# -

# Accepted values, in order of severity:
# "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]
format = "common"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS10"
  [entryPoints.traefik]
  address=":8080"

[acme]
email = "accounts@southcla.ws"
entryPoint = "https"
storage = "/etc/traefik/acme/acme.json"
acmeLogging = true
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

# -
# Web configuration
# -

[api]
entryPoint = "traefik"
dashboard = true
debug = true

# -
# Docker configuration
# -

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = true
watch = true
network = "gateway"

# -
# Metrics
# -

[metrics]
  [metrics.prometheus]
  entryPoint = "traefik"
